source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.1'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# gem 'rspec-rails', '>= 3.2.3'
# gem 'rspec' '>=3.2.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc
#for haml to html conversion
gem 'haml'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  # gem 'byebug'
  # gem 'debugger'
  gem 'cucumber-rails', :require => false
  gem 'cucumber-rails-training-wheels'
  gem 'database_cleaner'
  gem 'capybara'
  gem 'launchy'
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'
  gem 'rspec-rails'
  gem 'simplecov'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

#  source 'https://rubygems.org'

# ruby '1.9.3'
# gem 'rails', '3.2.18'

# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'

# for Heroku deployment - as described in Ap. A of ELLS book
# group :development, :test do
#   gem 'sqlite3'
#   gem 'debugger'
#   gem 'cucumber-rails', :require => false
#   gem 'cucumber-rails-training-wheels'
#   gem 'database_cleaner'
#   gem 'capybara'
#   gem 'launchy'
#   gem 'rspec-rails'
#   gem 'simplecov'
# end
# group :production do
#   gem 'pg'
# end

# # Gems used only for assets and not required
# # in production environments by default.
# group :assets do
#   gem 'therubyracer'
#   gem 'sass-rails'
#   gem 'coffee-rails'
#   gem 'uglifier'
# end

# gem 'jquery-rails'

# # Use unicorn as the web server
# # gem 'unicorn'

# # Deploy with Capistrano
# # gem 'capistrano'

# # To use debugger
# gem 'haml'